#!/usr/local/bin/perl

use PeGS::PDF;

my $W    = 3.25 * 72;
my $H    = 2.25  * 72;

my $pdf = PeGS::PDF->new(
	{
	file => "/Users/brian/Desktop/reference.pdf",
	x    => $W,
	'y'  => $H,
	}
	);
die "Could not create object!" unless ref $pdf;


my $foo = 'Buster';

my $array = [ qw( Mimi Buster Ginger Ella ) ];
my $length = 6;
my $scalar_width  = 10*$length;

$pdf->make_reference( '$cats', \$foo, 10, 130 );

my( $bottom_left_x, $bottom_left_y ) = ( 126.75, 120 );

$pdf->make_collection_bar(
	$bottom_left_x,
	$bottom_left_y - $pdf->connector_height - $pdf->black_bar_height,
	$scalar_width + 2 * $pdf->x_padding + $pdf->pointy_width,
	);
	
my $count = 0;
foreach my $value ( @$array )
	{
	$count++;
	$pdf->make_text_box(
		$bottom_left_x, 
		$bottom_left_y - $pdf->connector_height - $pdf->black_bar_height - $count*($pdf->font_height + 2 * $pdf->y_padding),
		$scalar_width  + 2 * $pdf->x_padding,
		$pdf->box_height, 		
		\ $value
		);
	}

$pdf->close;
